### ISSUE TITLE
Neovim hangs with the zig parser installed.

### ISSUE THREAD

**Issue by nextdimension** [nvim-treesitter/nvim-treesitter#2049]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

Neovim hangs with the zig parser installed, tried on nightly and stable nvim versions.
MacOS 12 and Arch linux.

### To Reproduce

Install neovim
Install this plugin.
enable this plugin
run :TSInstall zig
run :checkhealth nvim_treesitter or open a file with .zig extenstion

### Output of `:checkhealth nvim-treesitter`

```markdown
hangs nvim
```

### Output of `nvim --version`

```text
NVIM v0.5.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.1/build/config -I/build/neovim/src/neovim-0.5.1/src -I/usr/include -I/build/neovim/src/neovim-0.5.1/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.1/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

I have reported this issue here: https://github.com/maxxnino/tree-sitter-zig/issues/8
There was an issue raised in the zig parser repo previously but looks like the developer pointed to a problem with nvim-treesitter
and the issue was closed

This was working until yesterday. This commit might be the issue.
https://github.com/nvim-treesitter/nvim-treesitter/commit/ff2897e5b7ca8b4ce188696995c3b325a2f16412?diff=split

**Comment by maxxnino** [comment]
I tried update treesitter and generate new parser. It solve 3/5 problem. But it left two hanging query left. Don't know what cause the problem, it had been worked until now
```
;; #1
(PtrTypeStart "c" @variable.builtin)

;; #2
(
  (ContainerDeclType
    [
      (ErrorUnionExpr)
      "enum"
    ]
  )
  (ContainerField (IDENTIFIER) @constant)
)
```

**Comment by maxxnino** [comment]
@nextdimension hi, I just fixed the issue, can you update nvim-treesitter and reinstall parser. And check is it solve the problem

**Comment by nextdimension** [comment]
Thankyou, problem solved.

**Comment by numToStr** [comment]
I tried opening the following zig file and neovim died on me ;(

<details>
<summary>
demo.zig
</summary>

```zig
const std = @import("std");

const Game = enum {
    rock,
    paper,
    scissor,
};

const Union = union(enum) { Int: u8, String: []const u8 };

pub fn main() anyerror!void {
    const a: Game = .rock;
    const b = Game.paper;
    std.log.info("{} {}", .{ a, b });

    const u = Union{ .Int = 89 };
    const v = Union{ .String = &[_]u8{ 1, 2, 3 } };
    const w = Union{ .String = &[_]u8{ 'a', 'b', 'c' } };
    const x = Union{ .String = "hello" };
    std.log.info("{}", .{u});
    std.log.info("{}", .{v});
    std.log.info("{}", .{w});
    std.log.info("{s}", .{w.String});
    std.log.info("{}", .{x});

    switch (u) {
        Union.Int => |f| std.log.info("Union.Int: {d}", .{v}),
        Union.String => |f| std.log.info("Union.Int: {d}", .{v}),
    }

    const yo = switch (u) {
        Union.Int => |_| "Union::Int",
        Union.String => |_| "Union::Int",
        // else => undefined,
    };

    std.log.info("{s}", .{yo});
}
```
</details>

**Comment by maxxnino** [comment]
@numToStr https://github.com/nvim-treesitter/nvim-treesitter/pull/2052#issuecomment-983226682

**Comment by numToStr** [comment]
@maxxnino I am on now `nvim v0.7` and latest `nvim-treesitter` commit. I've also tried re-installing the parser and the issue still exists.

**Comment by maxxnino** [comment]
@numToStr what compiler are you using? I'm using zig, maybe because of that I don't have this issue. And what is your platform?

**Comment by numToStr** [comment]
@maxxnino I am on linux. And I think my compiler is gcc. I don't know how to change the compiler otherwise I would probably test with zig.

**Comment by Gaarco** [comment]
@maxxnino It's not the compiler, just tried with zig and Nvim (0.6) hangs in that case too.

**Comment by keith** [comment]
I'm seeing the same on macOS with nvim 0.6 even after forcing re-installing treesitter plugins. I might be missing something in the docs but is there a way to disable TS just for one language to avoid this?

**Comment by gpanders** [comment]
>is there a way to disable TS just for one language to avoid this?

`:TSUninstall zig`

**Comment by maxxnino** [comment]
This is my archlinux box with neovim 0.6. I really want to help, But It doesn't hang on me
https://user-images.githubusercontent.com/34153891/144412787-8dc7b4da-ef60-48d5-9a2f-4922c6274fd2.mp4

**Comment by maxxnino** [comment]
This is my archlinux box with neovim 0.6. I really want to help, But It doesn't hang on me

https://user-images.githubusercontent.com/34153891/144414618-e0614199-d87a-4445-ba9a-3da4499296ba.mp4

**Comment by maxxnino** [comment]
i'm using vagrant box with virtualbox backend not WLS

**Comment by maxxnino** [comment]
@Gaarco @numToStr can you change the following line below from`#match?` to `#lua-match?`. And check is it solve the problem
https://github.com/nvim-treesitter/nvim-treesitter/blob/acf0c0f6a10e384c86f2b162b20488af76d292be/queries/zig/highlights.scm#L8
https://github.com/nvim-treesitter/nvim-treesitter/blob/acf0c0f6a10e384c86f2b162b20488af76d292be/queries/zig/highlights.scm#L30
https://github.com/nvim-treesitter/nvim-treesitter/blob/acf0c0f6a10e384c86f2b162b20488af76d292be/queries/zig/highlights.scm#L39
https://github.com/nvim-treesitter/nvim-treesitter/blob/acf0c0f6a10e384c86f2b162b20488af76d292be/queries/zig/highlights.scm#L48

**Comment by nextdimension** [comment]
I've tried this on MacOS 12 with NVIM 5.1. I used the provided demo.zig and I have no problem either.

**Comment by Gaarco** [comment]
@maxxnino it doesn't solve the problem.

**Comment by numToStr** [comment]
@maxxnino I've also tried your changes but it didn't help.

**Comment by theHamsta** [comment]
Maybe related https://github.com/UserNobody14/tree-sitter-dart/issues/23

**Comment by numToStr** [comment]
It seems after https://github.com/neovim/neovim/pull/16606, the hang is gone but it still takes some time to load the first file (the second one loads fine).

**Comment by Gaarco** [comment]
Not fixed for me, waited 3 minutes and the file did not open.
It's pointless to try to wait more time since 3 minutes already exceeds an acceptable time.

**Comment by numToStr** [comment]
@Gaarco Did you reinstall the parser?

**Comment by Gaarco** [comment]
Yes

**Comment by maxxnino** [comment]
The problem is why it only happens on some machines

**Comment by stsewd** [comment]
Make sure neovim is compiled with the given version of tree-sitter, some distributions use their own version of tree-sitter (usually the latest tag) instead of the one pinned by neovim.

**Comment by Gaarco** [comment]
> Make sure neovim is compiled with the given version of tree-sitter, some distributions use their own version of tree-sitter (usually the latest tag) instead of the one pinned by neovim.

This was indeed the problem! Now it works.

**Comment by stsewd** [comment]
Looks like the problem was solved by updating tree-sitter.
