### ISSUE TITLE
Indentation: Support automatically unindenting line when typing closing block symbol (e.g. `}` in C)

### ISSUE THREAD

**Issue by Isopod** [nvim-treesitter/nvim-treesitter#2086]
**Is your feature request related to a problem? Please describe.**
When using the indentation feature of nvim-treesitter, closing block statements are not correctly unindented as you type them. For example, if you write a block in C, the closing `}` is indented to the same level as the inner statements rather than the opening brace:

```c
{
    statement;
    statement;
    }
```

When it should be like this:

```c
{
    statement;
    statement;
}
```

The same problem occurs with e.g. the `end` keyword in Lua/Ruby/Pascal etc. The indendation is correct when selecting the code and formatting with `=`, but not when typing in insert mode.

Legacy `filetype indent` handles this case correctly even in insert mode. Unfortunately, as long as treesitter indent does not handle this correctly, it can't really replace `filetype indent`.

**Describe the solution you'd like**
nvim-treesitter should recognize that a closing symbol was typed and automatically unindent it. 

**Describe alternatives you've considered**
You can select the code block in visual mode and press `=` to fix the indentation. This isn't practical, but it shows that rules for unindenting are already there. They just aren't applied in insert mode for some reason.

**Comment by stsewd** [comment]
Hi, we already have a module for indentation https://github.com/nvim-treesitter/nvim-treesitter#indentation, but is still in progress. But the main issue is that it depends on having the nodes available, and while you are writing the nodes aren't completed yet, so it doesn't always trigger the correct indentation. See https://github.com/nvim-treesitter/nvim-treesitter/issues?q=is%3Aissue+is%3Aopen+indentation for some already reported issues, feel free to open a new issue with the filetype you are having problems with if isn't already reported.

**Comment by Isopod** [comment]
I'm sorry if it wasn't clear: I am using the indentation module you mentioned. I am experiencing this problem with C and a [Pascal grammar](https://github.com/Isopod/tree-sitter-pascal/tree/nvim) I've been working on. I did search the bug tracker and could not find an existing issue for this, so can you please reopen this?

Here is a little video I just recorded:

https://user-images.githubusercontent.com/2358109/146633589-6d9b0a61-4e1d-4e60-9fbe-edff2740bd52.mp4

As you can see, the `}` is not unindented as I type it. But later, when I select the code and hit `=` to format, it works.

**Comment by Isopod** [comment]
Basically, I think that the problem is that at the time (before) the `}` is entered, the indentation is actually *correct*: It's inside the `if` statement, so the cursor *should* be indented. But the indentation needs to be removed after the `}` was inserted. The indentation module currently does not seem to support unindenting a line after the fact (as opposed to plain old `filetype indent`).

For comparison, here is the same sequence with treesitter indent turned off and `filetype indent` turned on:

https://user-images.githubusercontent.com/2358109/146665346-9569dd8d-2f9c-4a72-b8cf-54bac2e54a37.mp4

Observe how the line is indented at first but gets unindented after the `}` was typed. 

Here is a similar recording with Pascal (again with `filetype indent`) where you can see even better what is happening:

https://user-images.githubusercontent.com/2358109/146665450-3d01ad90-d6fa-4561-99a2-cf914b3e05b8.mp4

As soon as the `end;` keyword is recognized, the line is unindented. This is the feature I also want for treesitter indent.

**Comment by MunifTanjim** [comment]
For anybody stumbling upon this, in order to solve this, `nvim-treesitter` will need to support setting [`'indentkeys'`](https://neovim.io/doc/user/options.html#'indentkeys') somehow.

**Comment by theHamsta** [comment]
This was fixed probably by #2333 by doing a reparse on `{`

**Comment by Isopod** [comment]
It indeed appears to be fixed for C. Unfortunately, indentation for Pascal is now completely broken (I don't know if it is related to this change). Did something change about how the queries are interpreted? Do the queries need to be updated?

https://user-images.githubusercontent.com/2358109/152677832-27565044-f32d-4a7d-bfed-86d70e9a1961.mp4

**Comment by theHamsta** [comment]
@Isopod please have a look at `:h indentkeys`. You can control yourself when the indent function is called. Have a look at how it's configured in Lua. There the ftplugin automatically includes `end` for example to trigger re-indent

**Comment by Isopod** [comment]
I don't think it is related to that. Even when I select everything and force reindent  with `=` (like I did at the end of the clip), it's still broken.

**Comment by theHamsta** [comment]
Then, probably the queries need to be updated. I may have time for this, this evening. But usually it's better when a language user designs the queries. You can have a look at `tests/indent/` on how the tests are written which help a lot to change the behavior of the queries that they pass all test files. I think, that you probably have to change them to be more similar to the Lua queries which have recently been improved.

**Comment by Isopod** [comment]
@theHamsta I'm working on that now. Got it sort of working. One problem I face, however, is this:
```
if x then
_
```
Let _ represent the cursor. If I type this, the cursor is not indented.

This is due to the grammar, because unlike, say, C where a statement must always be terminated by a `;`, in Pascal it is legal to omit the last semicolon in a compound statement. What this means is that these are all valid syntax:

```
program foo;
begin
  if true then
    a;
end.
```

```
program foo;
begin
  if true then
    a
end.
```

```
program foo;
begin
  if true then
    ;
end.
```

```
program foo;
begin
  if true then
end.
```

The last one is a problem. Why? Because TreeSitter does not allow empty nodes. So the only way for me to support this in the grammar was to drop the node for the "then" clause in this case.

Compare ASTs for the following examples:
```
program foo;
begin
  if true then
    a
end.
```
```
program foo;
begin
  if true then
end.
```
```
...
      (if [2, 2] - [3, 5]
        (kIf [2, 2] - [2, 4])
        condition: (kTrue [2, 5] - [2, 9])
        (kThen [2, 10] - [2, 14])
        then: (statement [3, 4] - [3, 5]
          (identifier [3, 4] - [3, 5])))
...
```
```
...
      (if [2, 2] - [2, 14]
        (kIf [2, 2] - [2, 4])
        condition: (kTrue [2, 5] - [2, 9])
        (kThen [2, 10] - [2, 14]))
      (kEnd [3, 0] - [3, 3]))
...
```

Note how in the second example the "then" clause is missing.

The implication is that, as far as TreeSitter is concerned, the `if` statement is complete. Hence, it looks to nvim-treesitter as if the cursor is *after* the `if` statement rather than inside of it, so of course nothing is indented.

I'm not sure how to solve this. One workaround I've tried is to simply add all possible keys to the `indentkeys` expression. That way, the indentation is fixed as soon as you continue typing. Tbh, I'm not quite sure why this isn't the default -- wouldn't it make sense to reindent the line on every key press? Doing this by default would solve a number of other issues, which I am not going to mention here because this comment is already very long.

**Comment by theHamsta** [comment]
There is a similar problem for this in yaml, where each node after a full line might be complete. You might try to experiment whether disabling force re-parsing for Pascal (https://github.com/theHamsta/nvim-treesitter/blob/c1585004f464f8146f6cbeace9b639125dc218da/lua/nvim-treesitter/indent.lua#L7-L9) which is kind of a key (indentkeys might not work well then). Probably a cleaner solution would be to try to add a new capture with code for that situation.

Can you share your current state in a WIP PR?
