### ISSUE TITLE
Weird new install behavior: Vim E492: Not an editorr command: TSUpdate

### ISSUE THREAD

**Issue by ForsakenRei** [nvim-treesitter/nvim-treesitter#5536]
### Describe the bug

New to treesitter, in the document it said
```
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
```
So I put it into the plugin section and run `:PlugInstall` but it will always throw an error
![YIJJ TLXOOI16~G){5PR WS](https://github.com/nvim-treesitter/nvim-treesitter/assets/23041178/27cc64de-f9e7-45f1-9482-c47311c81b30)
But if I press R it will be fine. Is it expected? I only noticed it with a newly installed nvim-treesitter, if it was removed and reinstall then nothing happens. Tried on neovim 0.9.4(Ubuntu 22.04).

There seems to be an error in checkhealth as well but I'm not sure what's going on...

### To Reproduce

1. Install Neovim and vim-plug
2. Add `Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}` to `init.vim`
3. Run `:PlugInstall`
4. Error occurs, press R to retry
5. Press R to retry, it shows one line - nvim-treesitter: Already Installed

### Expected behavior

No error should happen if following the installation guide.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.16.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.0-86-generic",
  sysname = "Linux",
  version = "#96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ x
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR lua(injections): ...root/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 2992 for language lua
  lua(injections) is concatenated from the following files:
  | [ERROR]:"/home/{username}/.local/share/nvim/site/plugged/nvim-treesitter/queries/lua/injections.scm", failed to load: ...root/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 2992 for language lua
```

### Output of `nvim --version`

```text
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by liskin** [comment]
Same issue here, also nvim 0.9.4. Bisected to bfb4601f48c127ae6fb24a30ebf0495aaca8d28f. Reverting the lua-related parts (https://github.com/liskin/nvim-treesitter/commit/e8065ea60510353dae41beda0b67228e3f148c40) seems to fix the issue.

**Comment by lucario387** [comment]
That commit is falsy, yes.

The commit right after that has the fixup for those lua queries though

**Comment by ForsakenRei** [comment]
> That commit is falsy, yes.
> 
> Clason did push the fixup a few days after that, so it should not be an issue.

Thanks, I will give it a try in a clean environment later.

**Comment by liskin** [comment]
> Clason did push the fixup a few days after that, so it should not be an issue.

Well, but it clearly is. Here's a reproducer in a clean environment:

```dockerfile
FROM debian:unstable@sha256:0862a2d6f153cb5287d7a4e25869cb5a8852765e62ff370e970d9cfcc26658aa

RUN apt-get update -y
RUN apt-get install -q -y curl git
RUN curl -LSsf https://github.com/neovim/neovim/releases/download/v0.9.4/nvim-linux64.tar.gz | tar xz
RUN sh -c 'curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/ca0ae0a8b1bd6380caba2d8be43a2a19baf7dbe2/plug.vim'
RUN mkdir -p ~/.config/nvim \
 && echo "call plug#begin()" >>~/.config/nvim/vimrc.vim \
 && echo "Plug 'nvim-treesitter/nvim-treesitter', #{commit: '8996612bfbebe1657e1bb55a95201c96cab945c6'}" >>~/.config/nvim/vimrc.vim \
 && echo "call plug#end()" >>~/.config/nvim/vimrc.vim \
 && echo "vim.cmd.source(vim.fn.stdpath('config') .. '/vimrc.vim')" >>~/.config/nvim/init.lua \
 && :
RUN nvim-linux64/bin/nvim -c "PlugInstall" -c "qall" \
 && nvim-linux64/bin/nvim -c "TSUpdate" -c "qall"
RUN echo "require'nvim-treesitter.configs'.setup { highlight = { enable = true } }" >>~/.config/nvim/init.lua
```

```console
$ docker build -t nvim-treesitter-lua-bug .
$ docker run --rm -it nvim-treesitter-lua-bug:latest
# nvim-linux64/bin/nvim ~/.local/share/nvim/plugged/nvim-treesitter/lua/nvim-treesitter.lua
```

```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: /nvim-linux64/share/nvim/runtime/filetype.lua:24: Error executing lua: /nvim-linux64/share/nvim/runtime/fi
letype.lua:25: BufReadPost Autocommands for "*"..FileType Autocommands for "*": Vim(append):Error executing lua callback: ...-linux64/sh
are/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 2992 for language lua
stack traceback:
        [C]: in function '_ts_parse_query'
        ...-linux64/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get'
        ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:114: in function 'new'
        /nvim-linux64/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser'
        /nvim-linux64/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
        /nvim-linux64/share/nvim/runtime/lua/vim/treesitter.lua:459: in function 'start'
        ...lugged/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach'
        .../plugged/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
        .../plugged/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
        .../plugged/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <.../plugged/nvim-treesitter/lua/nvim-treesitter/co
nfigs.lua:132>
        [C]: in function 'nvim_cmd'
        /nvim-linux64/share/nvim/runtime/filetype.lua:25: in function </nvim-linux64/share/nvim/runtime/filetype.lua:24>
        [C]: in function 'nvim_buf_call'
        /nvim-linux64/share/nvim/runtime/filetype.lua:24: in function </nvim-linux64/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_cmd'
        /nvim-linux64/share/nvim/runtime/filetype.lua:25: in function </nvim-linux64/share/nvim/runtime/filetype.lua:24>
        [C]: in function 'nvim_buf_call'
        /nvim-linux64/share/nvim/runtime/filetype.lua:24: in function </nvim-linux64/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /nvim-linux64/share/nvim/runtime/filetype.lua:24: in function </nvim-linux64/share/nvim/runtime/filetype.lua:10>
Press ENTER or type command to continue
```

**Comment by liskin** [comment]
> That's a different error (incompatible queries in runtime path). You need to make sure of the correct priorities of parsers and queries between the bundled ones and plugins. Standard installs do that, but custom setups like yours are your responsibility.

Can you please elaborate about what is non-standard in that setup? Or how to make a more standard one? I just literally tried to use the most standard (i.e. not what I myself use) stuff in that Dockerfile to reproduce the issue, and I still triggered the bug. Where do I set non-standard priorities of parsers and queries?

**Comment by liskin** [comment]
I mean, yeah, this is a different error than the `Not an editor command: TSUpdate` in $subject. I kinda assumed that's a red herring and the real error we're talking about is the one in OP's `:checkhealth nvim-treesitter` output.

**Comment by liskin** [comment]
Right, I did some more experimenting and I see what you mean. The following Dockerfile makes it works:

```dockerfile
FROM debian:unstable@sha256:0862a2d6f153cb5287d7a4e25869cb5a8852765e62ff370e970d9cfcc26658aa

RUN apt-get update -y
RUN apt-get install -q -y curl git build-essential
RUN curl -LSsf https://github.com/neovim/neovim/releases/download/v0.9.4/nvim-linux64.tar.gz | tar xz
RUN sh -c 'curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/ca0ae0a8b1bd6380caba2d8be43a2a19baf7dbe2/plug.vim'
RUN mkdir -p ~/.config/nvim \
 && echo "call plug#begin()" >>~/.config/nvim/vimrc.vim \
 && echo "Plug 'nvim-treesitter/nvim-treesitter', #{commit: '8996612bfbebe1657e1bb55a95201c96cab945c6'}" >>~/.config/nvim/vimrc.vim \
 && echo "call plug#end()" >>~/.config/nvim/vimrc.vim \
 && echo "vim.cmd.source(vim.fn.stdpath('config') .. '/vimrc.vim')" >>~/.config/nvim/init.lua \
 && :
RUN nvim-linux64/bin/nvim -c "PlugInstall" -c "qall" \
 && nvim-linux64/bin/nvim -c "TSUpdateSync" -c "qall" \
 && nvim-linux64/bin/nvim -c "TSUpdateSync lua" -c "qall" \
 && :
RUN echo "require'nvim-treesitter.configs'.setup { highlight = { enable = true } }" >>~/.config/nvim/init.lua
```

Notice that I had to explicitly `TSUpdateSync lua` because `TSUpdateSync` doesn't update the lua parser!

The priorities are set correctly, `:echo nvim_get_runtime_file('parser', v:true)` returns `['/root/.local/share/nvim/plugged/nvim-treesitter/parser', '/nvim-linux64/lib/nvim/parser']`. It's just that `:TSUpdate` doesn't update any of the parsers shipped with neovim itself.

And I guess one might consider that a feature, hm. So I'll need to list all the parsers shipped with neovim in nvim-treesitter's `ensure_installed` otherwise it will crash whenever I open a lua file.

Anyway, I still wonder what's so non-standard about the Dockerfile? It just does what https://github.com/nvim-treesitter/nvim-treesitter#installation says, I belive.

**Comment by lucario387** [comment]
> because `TSUpdateSync` doesn't update the lua parser!

Well yes, because the lua parser bundled with neovim are not under nvim-treesitter's control, only those that nvim-treesitter installed are.


>  After all, `:checkhealth nvim-treesitter` does list those parsers, so it's strange and unexpected `:TSUpdate` doesn't update them.

I don't see nvim-treesitter listing parsers that I don't install using it, but is shipped with neovim. I tried `:TSUninstall markdown`, and when I do `:che nvim-treesitter` markdown is no longer in the list

**Comment by liskin** [comment]
Right, so the `Not an editor command: TSUpdate` is actually caused by vim-plug not knowing to load `plugin/**/*.lua` after installing the plugin. It [does load `plugin/**/*.vim`](https://github.com/junegunn/vim-plug/blob/ca0ae0a8b1bd6380caba2d8be43a2a19baf7dbe2/plug.vim#L440) but not `*.lua`. So this

```vim
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
```

instruction in the README has been broken since 07eb437bb1c4c0a0298553dd509294f82362d6bc (April 2022, quite a while then).

Shall we report this to https://github.com/junegunn/vim-plug/ then?

(I'll open a separate issue or PR for `:TSUpdate` ignoring neovim-shipped parsers.)

**Comment by lucario387** [comment]
idk, it's not under our control, so do what you think is correct.

**Comment by liskin** [comment]
> idk, it's not under our control, so do what you think is correct.

Well the other alternative¹ is to implement a workaround here by reintroducing `plugin/nvim-treesitter.vim` that makes sure `plugin/nvim-treesitter.lua` is loaded, kinda like they [used to do in catpuccin](https://github.com/catppuccin/nvim/blob/61f2e2e8a134b8430775c88ecd71beb3a6ff3ee9/plugin/catppuccin.vim). I found this while looking whether it's already been reported to vim-plug, and followed the trail from https://github.com/junegunn/vim-plug/issues/1207.

I don't know if people regularly perform `:PlugUpgrade`. If they don't, then working around it here would be preferable. I mean, you folks literally tell people to `Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}` first thing in the README, so perhaps it'd be good if it just worked?

¹) Well, not really an "alternative", I'll report it to vim-plug anyway because why not. It's just a question of whether you want a quicker solution before it's fixed in there and the fix gets to users.

**Comment by liskin** [comment]
> > because `TSUpdateSync` doesn't update the lua parser!
> 
> Well yes, because the lua parser bundled with neovim are not under nvim-treesitter's control, only those that nvim-treesitter installed are.

Not under its control, but it'll happily use those parsers, and then crash if they're not at the revision it expects… far from ideal.

> > After all, `:checkhealth nvim-treesitter` does list those parsers, so it's strange and unexpected `:TSUpdate` doesn't update them.
> 
> I don't see nvim-treesitter listing parsers that I don't install using it, but is shipped with neovim. I tried `:TSUninstall markdown`, and when I do `:che nvim-treesitter` markdown is no longer in the list

That's truly strange. What's your `:echo nvim_get_runtime_file('parser', v:true)` and what's in the directories it lists? Can you possibly try to reproduce using the Dockerfile from https://github.com/nvim-treesitter/nvim-treesitter/issues/5536#issuecomment-1803645369? Or if that's not how nvim-treesitter is meant to be set up, can you tell me what's wrong with that setup?

Might be best to continue this discussion in https://github.com/nvim-treesitter/nvim-treesitter/pull/3862, where it's actually relevant.

**Comment by wam** [comment]
> And I guess one might consider that a feature, hm. So I'll need to list all the parsers shipped with neovim in nvim-treesitter's `ensure_installed` otherwise it will crash whenever I open a lua file.

I think this could be noted higher in the readme:

```
-- A list of parser names, or "all" (the five listed parsers should always be installed)
  ensure_installed = { "c", "lua", "vim", "vimdoc", "query" },
```

Perhaps there could be a "minimum necessary `.setup` config" block, directly following the `Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}` part. (The word "should" could also be "must", but I'm not sure if that would be technically accurate.) The rest of the optional/recommended config could remain in the "Modules" section.

My main reason for suggesting this is because Lua is at the heart of many neovim configurations, so any error related to Lua parsing has the potential to be pretty confusing. It's an interesting situation when the plugin tries to parse the file that sets up the plugin, and something fails.

(My first question was "is this a problem with the lua parser itself, or is this a syntax error in my config file that the parser can't handle?" Second question was "Wait, where is this lua parser coming from? I didn't install it." I just didn't realize it was falling back to neovim's built-in.)

I think it's worth boosting this info a bit, but maybe I should propose an update to the community wiki installation instructions instead.

**Comment by clason** [comment]
We have already rewritten this whole functionality from scratch for the 1.0 release to avoid this kind of issues.

**Comment by wam** [comment]
> We have already rewritten this whole functionality from scratch for the 1.0 release to avoid this kind of issues.

Excellent, thank you! Looking forward to it.

**Comment by ForsakenRei** [comment]
> We have already rewritten this whole functionality from scratch for the 1.0 release to avoid this kind of issues.

Thank you and thanks everyone for the discussion here. I will close this issue and wait for the 1.0 release.

**Comment by liskin** [comment]
> I think this could be noted higher in the readme:
> 
> ```
> -- A list of parser names, or "all" (the five listed parsers should always be installed)
>   ensure_installed = { "c", "lua", "vim", "vimdoc", "query" },
> ```
> 
> (_I_ missed it, which is how I ended up at this thread)
> 
> Perhaps there could be a "minimum necessary `.setup` config" block, directly following the `Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}` part. (The word "should" could also be "must", but I'm not sure if that would be technically accurate.) The rest of the optional/recommended config could remain in the "Modules" section.

That bit is not only easy to miss, it's also incredibly confusing. What does "should always be installed" even mean?
* They're shipped in the neovim tarball, so it could well be interpreted as "these five should usually already be there"
* But as we've established in the discussion earlier, nvim-treesitter needs a specific revision of those parsers, so it's probably more of a "YOU should always list them here"
* Or is it actually "YOU MUST always list them here"? What's the usecase for not listing them?

Was my not having listed those 5 parsers in `require'nvim-treesitter.configs'.setup {…}` the reason why @clason referred to my reproducer as a "non-standard setup"? There are a bunch of us here being confused by the README so perhaps it's time to acknowledge that the docs for a "standard setup" may need some improvement?

And then we have the original issue of `{'do': ':TSUpdate'}` failing with vim-plug because it doesn't support (re)loading of `plugin/*.lua` after plugin installation, which is still unsolved as well. Why did we close the issue then?

**Comment by ForsakenRei** [comment]
Maybe I'm reading it wrong, the readme will be re-written for 1.0 release which should solve the parser problem(which I missed as well), or that's not totally the case?

Reopened and I will let the dev team decide if it's completed or not this time.

**Comment by edwardbeckett** [comment]
I'm experiencing the same effects at the O.P. Attempting to deduce a resolve from this thread is somewhat ambiguous. 

**_Q: Is this issue actually resolved or not?_** 

From what I've read so far, the fix is to update & reload the nvim-treesitter plugin. Is that accurate? 

Help would be appreciated.. 

`nvim -v`


>NVIM v0.9.5-dev-26+g57f1bc34f
Build type: RelWithDebInfo
LuaJIT 2.1.1692716794
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/space/Projects/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/space/Projects/neovim/.deps/usr/include -I/home/space/Projects/neovim/build/src/nvim/auto -I/home/space/Projects/neovim/build/include -I/home/space/Projects/neovim/build/cmake.config -I/home/space/Projects/neovim/src -I/usr/include -I/home/space/Projects/neovim/.deps/usr/include -I/home/space/Projects/neovim/.deps/usr/include -I/home/space/Projects/neovim/.deps/usr/include -I/home/space/Projects/neovim/.deps/usr/include -I/home/space/Projects/neovim/.deps/usr/include -I/home/space/Projects/neovim/.deps/usr/include
---


>system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/usr/local/share/nvim"

>Run :checkhealth for more info

**Comment by wam** [comment]
@edwardbeckett _for the meantime_, I think the best current fix that covers this entire conversation is as follows:

First, add the `ensure_installed` line to the plugin's `setup` function in your `init.lua`, with `"c", "lua", "vim", "vimdoc", "query"` (you can add any others that you want to the list, but these are mandatory). This ensures that treesitter will install its own compatible versions of those parsers, and not fall back to using the built-in parsers. The built-in lua parser seems to be the one that's incompatible.

```lua
require'nvim-treesitter.configs'.setup {
  ensure_installed = { "c", "lua", "vim", "vimdoc", "query" },
  -- ... any other configuration params here ...
}
```

Second, restart nvim. If you still get the error, run `:TSUpdate` manually and restart again. From that point onward, all should be well.

> Q: Is this issue actually resolved or not?

I think the answer is that it will be resolved _as of the 1.0 release_, because:

1. The _readme_ has been rewritten so that it uses lazy.nvim in the example instructions, and lazy.nvim doesn't have the same chicken-and-egg issue with vim-plug that throws an error during the first install. That's the original issue that started this thread, and the thread can be considered "resolved" at the time when following the quickstart in the readme no longer produces an error. The community wiki will need to be rewritten to cover the vim-plug example.
2. The _code_ has been rewritten so that it handles built-in vs treesitter-installed parsers more gracefully. I'm not sure the details on that.

As of the moment I'm writing this comment, installing vim according to the quickstart in the readme can fail (as you experienced), both because there's a chicken-and-egg problem inherent in the vim-plug `{'do': ':TSUpdate'}` hook, _and_ because the current version of treesitter is falling back on nvim's built-in lua parser, which is incompatible with it. 

These issues can appear to be related to each other if you're not familiar with the details of the plugin, even though they're actually separate errors. At least, that was my experience. Hence the back-and-forth in this thread.

**Comment by edwardbeckett** [comment]
@wam ~ Thank you for the rather excellent explanation. I'm not intimate with the details neovim, treesitter or vim-plug's dependency resolution implementation... hopefully this issue will be resolved in the @v 1.0  release...

**Comment by lutalli** [comment]
Still getting the issue from 2024 and [the fix](https://github.com/nvim-treesitter/nvim-treesitter/issues/5536#issuecomment-1826400562) mentioned by `wam` above worked for me.
