### ISSUE TITLE
Error in decoration provider treesitter/highlighter.line

### ISSUE THREAD

**Issue by podanypepa** [nvim-treesitter/nvim-treesitter#7115]
### Describe the bug

Error in decoration provider treesitter/highlighter.line:
Error executing lua: ...nvim-treesitter/lua/nvim-treesitter/query_predicates.lua:80: attempt to call method 'parent' (a nil value)
stack traceback:
        ...nvim-treesitter/lua/nvim-treesitter/query_predicates.lua:80: in function 'handler'
        ...cae8be91/share/nvim/runtime/lua/vim/treesitter/query.lua:758: in function 'fn'
        ...+gbcae8be91/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'match_preds'
        ...cae8be91/share/nvim/runtime/lua/vim/treesitter/query.lua:874: in function 'iter'
        ...91/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:313: in function 'fn'
        ...91/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:213: in function 'for_each_highlight_state'
        ...91/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:294: in function 'on_line_impl'
        ...91/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:370: in function <...91/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:364>

### To Reproduce

pen any file with go source code

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.23.0 (12fb31826b8469cc7b9788e72bceee5af1cf0977) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v22.7.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.3.9.4)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.6.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - angular             ✓ ✓ ✓ ✓ ✓
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ ✓ ✓
  - comment             ✓ . . . .
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . ✓ . ✓
  - dockerfile          ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . ✓
  - glimmer             ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - gomod               ✓ . . . ✓
  - gosum               ✓ . . . .
  - gowork              ✓ . . . ✓
  - hjson               ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - pem                 ✓ . ✓ . ✓
  - proto               ✓ . ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - svelte              ✓ ✓ ✓ ✓ ✓
  - tmux                ✓ . . . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.11.0-dev-700+gbcae8be91
Build type: RelWithDebInfo
LuaJIT 2.1.1724512491
```

### Additional context

<img width="1488" alt="Screenshot 2024-09-02 at 11 15 14" src="https://github.com/user-attachments/assets/817e0dd0-4d9f-469a-9823-92e623fc9c16">

**Comment by clason** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/7114

**Comment by ranamashood** [comment]
@clason
How can I disable this until your PR is merged? Neovim is currently unusable.

**Comment by 231tr0n** [comment]
Hi. Till this error is fixed, what commit of nvim-treesitter should i fallback to. I am currently not able to edit any go files because of this bug. Can someone please help me in figuring this out.

**Comment by clason** [comment]
This is a breaking change in Neovim, not this plugin. Don't use nightly.

**Comment by 231tr0n** [comment]
> This is a breaking change in Neovim, not this plugin. Don't use nightly.

Thank you soo much. It works if i switch to latest using bob.

**Comment by SerhiiMaksymivQAMadness** [comment]
sorry, how to fix this issue?
i dont use nightly
```
NVIM v0.11.0
Build type: RelWithDebInfo
LuaJIT 2.1.1741730670
```
and im on latest (master) nvim-treesitter, and still have this issue with go

**Comment by mateusz834** [comment]
> sorry, how to fix this issue?
i dont use nightly

For me `mv ~/.local/share/nvim ~/.local/share/nvim-back` helped, after plugin reinstall now i do not see any errors.
